name = "ClearDeck"
version = "1.0.0"
link = "https://github.com/ZeroPoke/crankshaft-cleardeck"
source = "https://github.com/ZeroPoke/crankshaft-cleardeck"
min-crankshaft-version = "0.2.2"

[author]
name = "ZeroPoke"
link = "https://github.com/ZeroPoke/"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = true
	menu = true
	quick-access = false

[store]
description = """
Removes the blur and background when opening the MainMenu and the Quick Acess Menu.
"""